spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/api/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

